workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:

      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - deveshchaudhary@gmail.com


release-workflow:
  name: Native Android
  max_build_duration: 60
  environment:
    vars:
      CM_KEYSTORE: $keyStore
      CM_KEYSTORE_PASSWORD: $storePassword
      CM_KEY_ALIAS_PASSWORD: $keyPassword
      CM_KEY_ALIAS_USERNAME: $keyAlias
  scripts:
    - name: Build release apk
    # set up release keystore
  storePassword :$storePassword
  keyPassword: $keyPassword
  keyAlias: $keyAlias
  storeFile :$keyStore

  artifacts:
    - app/build/**/outputs/**/*.apk
  publishing:
    email:
      recipients:
        - sbis1999@gmail.com